# Generated by Django 5.2.7 on 2025-10-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(max_length=10),
        ),
    ]
