# Generated by Django 5.2.7 on 2025-10-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0004_blooddonation_bloodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='units_donated',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='units_requested',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
